# The sequence is generated by the sum of starting number 1
# then starting number plus itself; 1+1
# then the number generated plus the previous number; 2+1
# next step is the sum of the number generated plus two last numbers; 3+2+1
# and the sequence continues the next step is the number generated plus two last numbers; 6+3+2 ...

n = int(input("Enter the length of the sequence: ")) # Do not change this line

num_gen = 0
first_previous = 1
second_previous = 2
i = 1
#loop for each in range of the given number
for each in range(n):
    #check if the starting number is equal to 1 and then increment by 1
    if (i == 1) :
        next_seq = 1
        i = i+1
        #continues to second
    #Second check if i==2 the next sequence is equal 2 and increment i by 1
    elif (i == 2): 
        next_seq = 2
        i+=1 #continue to 3 but here we apply different conditions
    else:
        #the next number of sequence is the number generated + first previous + second previous
        next_seq = num_gen + first_previous + second_previous
        num_gen = first_previous
        first_previous = second_previous
        second_previous = next_seq
    print(str(next_seq))